"""added posts table

Revision ID: af841657b7d1
Revises: 
Create Date: 2022-02-06 12:53:08.384447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af841657b7d1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
