"""add comment model

Revision ID: 304bccf31731
Revises: 861e102efab9
Create Date: 2022-02-10 20:29:05.660354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "304bccf31731"
down_revision = "861e102efab9"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("hashed_password", sa.String(length=60), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=32), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(length=32), nullable=True),
        sa.Column("hashed_password", sa.VARCHAR(length=60), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("comments")
    op.drop_table("users")
    # ### end Alembic commands ###


def upgrade_dev():
    pass


def downgrade_dev():
    pass
