"""added users table

Revision ID: 4caf3d991f5b
Revises: 736d5ff3ac37
Create Date: 2022-02-07 11:07:03.072754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4caf3d991f5b"
down_revision = "736d5ff3ac37"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("password", sa.String(length=60), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###


def upgrade_dev():
    pass


def downgrade_dev():
    pass
