"""added posts table

Revision ID: 4f933ea8db2e
Revises: 20d9ccd68dcb
Create Date: 2022-02-05 20:52:09.263848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f933ea8db2e"
down_revision = "20d9ccd68dcb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account")
    op.drop_table("student")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student", sa.Column("id", sa.VARCHAR(length=25), nullable=False)
    )
    op.create_table(
        "account",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("description", sa.VARCHAR(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
