"""renamed password column

Revision ID: 861e102efab9
Revises: 4caf3d991f5b
Create Date: 2022-02-07 20:34:12.855076

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "861e102efab9"
down_revision = "4caf3d991f5b"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", new_column_name="hashed_password")
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "hashed_password", new_column_name="password")
    # ### end Alembic commands ###


def upgrade_dev():
    pass


def downgrade_dev():
    pass
