sudo: required
language: python
python:
- 3.6
services:
- postgresql
- docker

env:
  global:
  - DATABASE_HOST=localhost
  - APP_PORT=80
  - APP_LOG_DIR=`pwd`/log
  - secure: xGcl0xB/3dFh2eRZCCc2TmxlILYE4NkieNix4qYtg25+iYd99TcLDecBCzRDUrxjPWtJFIAYZ1uzCqxYOKSxmbmWB6Hx8nhaLF5xCChv353wcaDy8XXDqjmMZ65+dgAP4JJAIkwr+qrFvsqxk8WnOINvgPjDU4a2OQBUzsJRyUq/jRlVoe9eqjrz0wShavqTcaBddrhx9UFwAoKtn2EiEg8ymwo6e8PQytiuE1gLWxC59xwiycgXKOsjsgiNqAEYRoE91TtG7cyiFxTcZnK9v7CJ+oTk65nDMRXRqn/SbvLIexWl5uzZqm/RyFlRiHGmN6YqA62tKM/bC6TJIF+V0ipjQ9qPESM9MOttyw5gtp14UYHXER7nlCGIYEfLiD4ms7ua1gwI0paMtaU8UlBWH+rXMbo8t4FPiWXuisiN3gF4KemPqMmnRFFn8F3c/9uERTxxXkkUCUAs5jy3b8Q1kCJU9/Gp8o1T2SQBYXVNrp9xAV7hcMUoVjdNAWX0yUzcmk8hydCIvdAS2PxHqw/KXNUVvDwNd5eeibwXrt1A8yPrdi83vNkS2MwQosDTf4olseAoOtAvZYKGsc4NxyFvJYPo6BudLFNOpza821145ECGPYpE/nn8BMzTaxR+Yt/864YNAtKUsxswMu75Ttc3MGOp2IjnosP1XdlZqFnoUM8=
  - secure: WAE/9Yg/zyInu+mxOrwS1FMzQGzvGQwDAgr2TkHWbSmMw7M+jYBiCasQZLQe649NoTDw03xlfkN7RoMamZWNO5K22TYD+i1lfO0nbsJQiNXCyRyAGvFyXEN9ejBq9QfNPL8hrFZpIlvQowxHhBt5pOYen7+YPp3mZETN+hm0bhC23Di+aU1tjH+tnY9xyBUFRKCyUehR7H0icBiPm1KyfzjURGcUtxwliEgT2nzwJeoP9Duf8AqAyVhcwLFUdJLPNdkOURotp6fajjF5FkyswSco/K/hlA0VDNRPjCkINn/jQCoh60OiojG+dEJIi0RjG/Q6ixVtLTR+tRu2d7GmoheXSRMnW8JNiacDIEM458fL/iFiobdERq4m12y6UBdDGYmAb4uj5wy/SN/zg0j/3ObA9yV1r30WrnEDGRaWPAnR2uXW3R+DNboE0cah4I4Xk5sFJ0u2N1y3srXJYZ9JP1EuW1XpcugVHRRSUJHGlNsklol29idDAt32L4cbQVG5qpCglzpulqHhOql79WHXMTtKqnmWKKYUk5hr59Em3x2Oq111U0HbmNiOP7UP+M373OHFfU4z2FXVyMMkqINZmI8m13cvHvFNPgzRwf3J05u1L3V8ns+615+I6vkONhqS34eBGXZ0Vhe61Jy5H7UDT3CwUgTQZN9k6j5LtO9D5z4=
  - secure: T2mPhQ8U5DhrY6knlL1UhrTcALPLJCITaXwjV51fpcY0dJK+3FHN/ju/6DS4t2Zb6GSDTim3XteQIM7wiTCNrxXEfFmvCRTKY/2TcHz7QYejZMjEGvUWFCZTgfLKKms68Ait11MnybWDR2zp4VLkdJMhu/jLApIXtvKvR/aoC6A7LXW3BjYzoQ505f85QHJemdpj21Y9ZNockjM+K6sxPyKLWfthE2W+Ak9n4QoBglvrPVAeEkmMtpac+BT/T6acf0Sy8444AgKBTfHVsAAy21r9n4Ogutq9/wh1CixOpmiycN4MdBYJxrL6CyVysD1+dep5368GO9DI0l6iPw8z6iuCZ2fAOLAsczK3Y3Wm2/qYnAbCbHdhGrQfjpVNVs2H64fp23MoyiwMpILYf9OeMUXo0YROlN1i0ZBc1bPEpp89PEgvuvRqwroC51tEF8SGTeNsBjBYoeAtY3xpO1fgdVc+RVe6am/MjCALkwo9BX/NKZihMyUB0Jd0hrf82aBX6wVNRAt3HX+hY0L6wZx1r8dRU1KlsR7K2P59f7RB6/B9g+PLvpo7Y/+rXrylFlGmtBuvHUAq6UNuI9fPrhJKjzJ5T/yVUwrMieJyADfA4iLFr84AT9l6J87SLvURA8UJadb8C2eJJCvMDCAZhljO191C/Geltf7KrOopEAFk9eU=
before_install:
- psql -f ./db/container-files/docker-entrypoint-initdb.d/db.sql -U postgres
- cd ./app
install:
- pip install -r requirements.txt
before_script:
- mkdir -p $APP_LOG_DIR
script:
- ./bin/run-tests
- coveralls
- git clean -xfd && docker build -t ihsw/py-lyfe ../
- ../bin/docker-push ihsw/py-lyfe
