"""add user roles

Revision ID: 23ee4487433d
Revises: 8ec97ada4afa
Create Date: 2022-02-19 19:43:14.056698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23ee4487433d"
down_revision = "8ec97ada4afa"
branch_labels = None
depends_on = None

role_names = ["admin", "regular"]


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###

    for role_name in role_names:
        op.execute(roles_table.insert().values(name=role_name))


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("roles")
    # ### end Alembic commands ###


def upgrade_dev():
    pass


def downgrade_dev():
    pass
