name: py-lyfe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        cd app
        poetry install
    - name: Lint with flake8
      run: |
        cd app
        poetry run flake8 ./py_lyfe --max-complexity 10 --exclude ./app/alembic
    - name: Run migrations for integration tests
      run: |
        cd app
        poetry run alembic -x db=test upgrade head
    - name: Test with pytest
      run: |
        cd app
        poetry run coverage run -m pytest
    - name: Upload coverage to coveralls.io
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd app
        poetry run coveralls --service=github
